# Generated by Django 2.1.3 on 2020-01-03 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200102_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='clusters',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
